### ISSUE TITLE
The process cannot access the file because it is being used by another process: 'help_crack.res'

### ISSUE THREAD

**Issue by industrialsociety** [RealEnder/dwpa#101]
Have 3 machines running `help_crack.py` and on one of them I am getting this intermittently. Only way to clear it is fully reboot the machine.

Traceback (most recent call last):
  File "C:\Users\x\help_crack.py", line 938, in <module>
    hc.run()
  File "C:\Users\x\help_crack.py", line 895, in run
    os.unlink(self.conf['res_file'])
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'help_crack.res'
PS C:\Users\x\hashcat-6.2.3>

**Comment by RealEnder** [comment]
Use separate hashcat/john copies on the three machines. help_crack.py writes temporary files with one and the same name, so running several instances from the same directory will not work.
