### ISSUE TITLE
distutils removal in python 3.12

### ISSUE THREAD

**Issue by rel0gic** [RealEnder/dwpa#104]
As described here (https://docs.python.org/3.11/whatsnew/3.10.html#distutils-deprecated) distutils is removed in python 3.12 -> Replace StrictVersion

According to [this](https://github.com/pypa/setuptools/discussions/3145#discussioncomment-4338944) it should be replaced with packaging.version.parse

**Comment by RealEnder** [comment]
Had to implement version compare from scratch, since I want help_crack.py to use only standard python modules.
This is fixed in version 2.0.0.
Please update.
