### ISSUE TITLE
wpa-sec.stanev.org down

### ISSUE THREAD

**Issue by retiolus** [RealEnder/dwpa#105]
The site is down
![image](https://github.com/RealEnder/dwpa/assets/65604466/8125e50c-a55c-45a7-b658-cf8d2651c43a)

**Comment by its0x08** [comment]
It's down again.

**Comment by RealEnder** [comment]
Sorry about this, there is an issue with the DB, but will be able to access it in Monday, 8 July. If I manage to restore remote access - earlier.

**Comment by poornachandratejasvi** [comment]
Still down

**Comment by RealEnder** [comment]
Yep, it was a failed SSD, which silently corrupted data.
Nasty, ugly stuff, but no dataloss :)

**Comment by RealEnder** [comment]
I do, but recovery takes too much time now. Will have to change the backup and restore strategy :) + to throw out the 10+ years old "server" :)

**Comment by kimocoder** [comment]
10 years .. yeah it's time 👍 nothing lasts forever, anymore in tech
