### ISSUE TITLE
The field `dicts`.`rules` is missing in the provided SQL schema.

### ISSUE THREAD

**Issue by iganev** [RealEnder/dwpa#109]
The field `dicts`.`rules` is missing in the provided SQL schema.  

This causes fatal error in `get_work.php` during dictionary selection, which on the other hand causes the `help_crack.py` worker to throw "no nets" error and exit.  

Furthermore, the `create_gz.sh` shell script also omits this field and no default rules are therefore being provided. This causes `help_crack.py` to exit even after manual introduction of the missing field into  the schema.

---

Another potential issue worth mentioning is the defined length of `nets`.`struct`. Is the length 393 backed by some specific requirement, or is it arbitrary? I am pretty sure some M2M3/M2/A captures are longer than that and could get truncated (and thus invalidated) during insertion.

**Comment by RealEnder** [comment]
You're right, still haven't updated the SQL, will do.
Meanwhile, if you have old installation, try the DB migration script here: https://github.com/RealEnder/dwpa/blob/master/misc/migrate_to_m22000.php

**Comment by iganev** [comment]
Thank you for the quick response and the quick update. I am setting up a blank new installation and noticed some minor issues like the abovementioned.

**Comment by RealEnder** [comment]
Just updated install instructions and scripts, please check them out. Also you'll notice some currently unused tables in the DB, these are WIP :)
