### ISSUE TITLE
dwpa doesn't accept pcap files from wlandump-ng

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#11]
As I saw the recommendation to use wlandump-ng I decided to give it a try, however it looks like dwpa doesn't accept any of the pcap files produced by it, I'm constantly getting "Bad capture file" errors while I try to upload the capture. Checking the file with wlanpcapinfo seems to pass fine:
```
[user@host hcxtools]$ ./wlancapinfo -i test.cap 
input file.......: test.cap
magic file number: 0xa1b2c3d4 (cap/pcap)
major version....: 2
minor version....: 4
data link type...: 105 (DLT_IEEE802_11) [http://www.tcpdump.org/linktypes.html]
packets inside...: 13438
last pcap error..: flawless
```
aircrack-ng and pyrit also recognize the file and show the handshakes in it.

Is any additional processing required prior submitting the pcap dumps from wlandump-ng or they can be uploaded as they are?

**Comment by RealEnder** [comment]
This should be OK now.

**Comment by strasharo** [comment]
Yep, works fine.
