### ISSUE TITLE
Doubts

### ISSUE THREAD

**Issue by freitas666** [RealEnder/dwpa#110]
Hello, 

I would like to know when  use hash_crack.py it check only my "uploads" or check all uploads by users in website?  IF check all, can i check a local.pcap using hash_crack.py??

Thanks : )

**Comment by RealEnder** [comment]
Hi,
help_crack works with all uncracked hashes, submitted by all users. You can always extract the heeded hashes with hcxpcapngtool, part of [hcxtools](https://github.com/ZerBea/hcxtools) and throw some dictionaries. You can start by downloading the [C-nets](https://wpa-sec.stanev.org/dict/cracked.txt.gz).
Cheers!
