### ISSUE TITLE
Why cant't go below 6.2.6 version?

### ISSUE THREAD

**Issue by FFAMax** [RealEnder/dwpa#113]
Hello, Alex. 
I see one reason before we had - 22000 support.
For now I found in helper 6.2.6 is hardcoded as a requirement.
That a significant limitation for using existed setups.
(if we talk about production where software sticked to Long Term Support may not be updated to new version for a years until old one is compromised or new features required)

**Comment by RealEnder** [comment]
The big benefit of m22000 for hashcat is it will reuse PBKDF2-SHA1 4096 iterations over handshakes and PMKIDs. This is great for such large-scale attacks.
It's very easy to compile the current hashcat head and use it locally, without the need to use the older system packages.
Also, john works out of the box for now, but I've still hadn't implemented rules support, which is in the works.

**Comment by FFAMax** [comment]
I mean we sticked to the latest one (6.2.6), probably it compatible with earlier versions. I mean if no reason to use latest one and older may work (which providing features) by allowing to use them will have more compatible system to just download and run - easy start, more people can contribute.

**Comment by RealEnder** [comment]
v6.2.6 had some fixes around m22000. Also, it was released back in 2022, so it's pretty widespread.
