### ISSUE TITLE
Syntax error when importing wpa.sql

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#12]
So I gave a try to the latest code and got this while trying to import wpa.sql on an empty database:
```
[root@test db]# mysql -u root -p dwpa < wpa.sql 
Enter password: 
ERROR 1064 (42000) at line 240: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
```
Also via PMA:
![image](https://user-images.githubusercontent.com/3337997/36067805-1aaa58f8-0ece-11e8-9b42-f92332f83897.png)

**Comment by RealEnder** [comment]
Just hit this myself, PMA doesn't cope well with events. The plan is to move this in external cron, mysql events are not enabled by default anyway.

**Comment by RealEnder** [comment]
Also, there are some misses in wpa.sql, will update it shortly.

**Comment by strasharo** [comment]
Thanks a lot, imports fine after the fix.
