### ISSUE TITLE
Submitted networks are not associated to user who submitted them

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#13]
So I grabbed the latest code and submitted some networks for testing. On submit I got this warning:

`Warning: Parameter 2 to mysqli_stmt::bind_param() expected to be a reference, value given in /var/www/wpacracker/public_html/common.php on line 343 Call Stack: 0.0001 234240 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 239224 2. include('/var/www/wpacracker/public_html/content/submit.php') /var/www/wpacracker/public_html/index.php:182 0.0009 240656 3. submission() /var/www/wpacracker/public_html/content/submit.php:36 0.0217 316032 4. insert_n2u() /var/www/wpacracker/public_html/common.php:486 0.0220 320840 5. call_user_func_array:{/var/www/wpacracker/public_html/common.php:343}() /var/www/wpacracker/public_html/common.php:343 Capture submitted successfully `

The networks were added successfully and they're visible in the common "Nets" view, however they don't appear in the "My nets one". Also the "n2u" table is completely empty, there were no entries created there.

**Comment by RealEnder** [comment]
Thanks for the headsup, this was easy to miss :)

**Comment by strasharo** [comment]
Thanks a lot for the fast fix, it's now resolved.
