### ISSUE TITLE
Multiple handshakes download and processing with same ssid

### ISSUE THREAD

**Issue by RealEnder** [RealEnder/dwpa#18]
Fetch all handshakes with the same essid to do ssid precomputation just once for current dictionary.
This will require pot file processing for hashcat instead of just PSK result in key file.

**Comment by ZerBea** [comment]
That is a big enhancement, because we save GPU time. If a contributer adds his own wordlist, we can check this list against all networks using the same ESSID. That wiil increase speed up to (2*4096)-1.

**Comment by RealEnder** [comment]
Fixed, now in prod.
