### ISSUE TITLE
Bug in help_crack.py when using oclHashCat/cudaHashCat

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#2]
There's some small bug in help_crack.py when using cudaHashCat. When we launch help_crack.py for the second time the challenge fails, because the password from the previous challenge is already saved in the cudaHashCat.pot file. Removing the pot file manually resolves the issue.

**Comment by RealEnder** [comment]
This should be fixed in ec453143a60f410f91d2aa272fb83c92678450e1.
Can you try with help_crack.py from git master?

**Comment by strasharo** [comment]
Sure, will try it now. I was using http://wpa-sec.stanev.org/hc/help_crack.py when I got it.

**Comment by strasharo** [comment]
Same situation with the file from git:

[root@CUDA stanev]# grep -ni pot help_crack.py 
488:            cracker = '%s -m2500 -w 3 --potfile-disable --outfile-format=2 -o%s %s %s %s' % (tool, key_file, rule, net_file, dictname)
[root@CUDA stanev]# ./help_crack.py 
help_crack, distributed WPA cracker, v0.8.5
site: http://wpa-sec.stanev.org/
Session resume
cudaHashcat v1.31 starting...

Device #1: Quadro FX 5800, 4095MB, 1296Mhz, 30MCU
Device #2: Tesla C1060, 4095MB, 1296Mhz, 30MCU
Device #3: Tesla C1060, 4095MB, 1296Mhz, 30MCU

Hashes: 1 hashes; 1 unique digests, 1 unique salts
Bitmaps: 8 bits, 256 entries, 0x000000ff mask, 1024 bytes
Rules: 1
Applicable Optimizers:
* Zero-Byte
* Single-Hash
* Single-Salt
Watchdog: Temperature abort trigger set to 90c
Watchdog: Temperature retain trigger set to 80c
Device #1: Kernel /root/cudaHashcat-1.31/kernels/4318/m02500.sm_13.64.ptx
Device #1: Kernel /root/cudaHashcat-1.31/kernels/4318/bzero.64.ptx
Device #2: Kernel /root/cudaHashcat-1.31/kernels/4318/m02500.sm_13.64.ptx
Device #2: Kernel /root/cudaHashcat-1.31/kernels/4318/bzero.64.ptx
Device #3: Kernel /root/cudaHashcat-1.31/kernels/4318/m02500.sm_13.64.ptx
Device #3: Kernel /root/cudaHashcat-1.31/kernels/4318/bzero.64.ptx

INFO: removed 1 hash found in pot file

                                             
Session.Name...: cudaHashcat
Status.........: Cracked
Input.Mode.....: File (challenge.txt)
Hash.Target....: Guest (00:18:39:b2:06:ed <-> 04:1e:64:4b:83:08)
Hash.Type......: WPA/WPA2
Time.Started...: 0 secs
Speed.GPU.#1...:        0 H/s
Speed.GPU.#2...:        0 H/s
Speed.GPU.#3...:        0 H/s
Speed.GPU.#*...:        0 H/s
Recovered......: 1/1 (100.00%) Digests, 1/1 (100.00%) Salts
Progress.......: 0/0 (100.00%)
Skipped........: 0/0 (100.00%)
Rejected.......: 0/0 (100.00%)
HWMon.GPU.#1...: -1% Util, 73c Temp, 35% Fan
HWMon.GPU.#2...: -1% Util, 74c Temp, 40% Fan
HWMon.GPU.#3...: -1% Util, 65c Temp, 35% Fan

Started: Tue Dec  1 09:43:53 2015
Stopped: Tue Dec  1 09:43:56 2015 
Challenge solving failed! Check if your cracker runs correctly.
[root@CUDA stanev]# cat cudaHashcat.pot 
Guest:001839b206ed:041e644b8308:password1234
[root@CUDA stanev]# 

[root@CUDA stanev]# cudaHashcat64.bin --help | grep -i pot
       --potfile-disable             Do not write potfile
[root@CUDA stanev]# 

JFYI, I'm using an older version of cudaHashCat (1.31) because of the hardware, but it still has the disable potfile arg available.

**Comment by RealEnder** [comment]
Yes, my bad, it was fixed only with Hashcat.
Can you try again the HEAD?

**Comment by strasharo** [comment]
Yep, it's perfect now. Thanks a lot, Alex. :+1:
