### ISSUE TITLE
Unable to import networks from a pcap file

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#3]
Hello. I setup an instance of dwpa for testing and it appears to be working at first glance, however when I upload a pcap dump with handshakes from besside-ng it states "Capture submitted successfully", but  nothing gets imported in the database and I can't see anything in "My nets" and in the corresponding database tables.  I see that the cap files are successfully being saved in the defined CAP dir. Also account registration works, so it has no issues writing to the database.
Any idea what might be wrong with the setup?

**Comment by RealEnder** [comment]
Check if external tools, defined in conf.php can be executed from php.
Also, you have to compile wpaclean version from here:
https://github.com/RealEnder/dwpa/tree/master/misc/wpaclean

**Comment by strasharo** [comment]
Yep, the WPACLEAN variable in conf.php is pointed to the locally compiled version of wpaclean bundled with dwpa. It produces the following output when ran against the sample file from aircrack-ng (initally i pointed it to the local wpaclean, however dwpa complained about the pcap files being corrupted, so that's where i realized that it's using a custom wpaclean and i pointed it to the proper one which made the error go away):

root@host:/var/www/public_html/cap# sudo -u www-data ./wpaclean /var/tmp *.cap
Net 00:0b:86:c2:a4:85 mic 56f98b98da5d55e3be396b43c7eb012a linksys
root@host:/var/www/public_html/cap# 

root@host:/var/www/public_html/cap# ls -la /var/tmp/*.cap
-rw-r--r-- 1 www-data www-data 487 Jun 18 21:53 /var/tmp/56f98b98da5d55e3be396b43c7eb012a.mic.cap
root@host:/var/www/public_html/cap# aircrack-ng /var/tmp/*.cap
Opening /var/tmp/56f98b98da5d55e3be396b43c7eb012a.mic.cap
Read 3 packets.

   #  BSSID              ESSID                     Encryption

   1  00:0B:86:C2:A4:85  linksys                   WPA (1 handshake)

Choosing first network as target.

Opening /var/tmp/56f98b98da5d55e3be396b43c7eb012a.mic.cap
Please specify a dictionary (option -w).


Quitting aircrack-ng...

cap2hccap is also locally compiled and executable from the web server account.
pyrit is also executable by www-data (had to alter the ownership of /root/.pyrit in order to make a permission denied error go away)

**Comment by RealEnder** [comment]
hm, try to clean cap file with pyrit like this:
pyrit -r <your.cap> -o strip.cap strip
then try to upload strip.cap

**Comment by strasharo** [comment]
Okay, just stripped the cap file using pyrit which produced a cap file with handshakes for 29 networks (all sorts of states good, bad and workable). Uploaded it to dwpa, got "Capture submitted successfully", however no networks were submitted to the database. I see that the capture file was copied as <myclientip>-c5958b5796259245fc3ae40baa1de0da.cap in the CAP directory. Same file works fine with dwpa hosted on http://wpa-sec.stanev.org/ (even prior the stripping with pyrit).

**Comment by strasharo** [comment]
During the install I imported both of the sql files included here without altering anything:
https://github.com/RealEnder/dwpa/tree/master/db

Do I need to modify something prior the import?

**Comment by RealEnder** [comment]
For sure you have to update some values in wpa-data.sql - like your dict locations, autoincrements and stats for example. Make sure cracked.txt.gz is on the same server, since it's written based on positives. Also you have to keep the name the same as in conf.php.
Your best bet for debugging this is to put some output in submission function:
https://github.com/RealEnder/dwpa/blob/master/web/common.php#L141
Maybe it's time to write a proper install for this :)

**Comment by djingibi** [comment]
Hello,
I also wait for a proper installl :)

Best Regards

**Comment by RealEnder** [comment]
I'm doing some DB redesign, next thing will be install script

**Comment by RealEnder** [comment]
Please check [INSTALL.md](https://github.com/RealEnder/dwpa/blob/master/INSTALL.md) for instructions.
