### ISSUE TITLE
help_crack: Hashcat on Windows can't pass challenge

### ISSUE THREAD

**Issue by modulusshift** [RealEnder/dwpa#35]
Hashcat on Windows can't pass challenge in help_crack.py. This seems to be because Hashcat seems to respect the conventions of the local OS in text files and ends a line with \r\n in Windows, where the script only expects \n. 

https://github.com/RealEnder/dwpa/blob/fcebbd4b56b197a36075d04fd57ab26c2ed2147a/help_crack/help_crack.py#L631

I edited this line 631 to include a \r in the rstrip and it passed the challenge and got to work.

**Comment by RealEnder** [comment]
Thanks for the heads-up, will check it also on other places.
