### ISSUE TITLE
Undefined index: n_state in common.php on line 754

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#37]
Not sure if it's related #27 , but after some of the recents updates (I recreated my db multiple times from scratch) I'm getting the following error in "My nets" view:
`Notice: Undefined index: n_state in /var/www/wpacracker/public_html/common.php on line 754 Call Stack: 0.0001 231480 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 236656 2. include('/var/www/wpacracker/public_html/content/my_nets.php') /var/www/wpacracker/public_html/index.php:182 0.0024 248544 3. write_nets() /var/www/wpacracker/public_html/content/my_nets.php:33 Notice: Undefined index: n_state in /var/www/wpacracker/public_html/common.php on line 754 Call Stack: 0.0001 231480 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 236656 2. include('/var/www/wpacracker/public_html/content/my_nets.php') /var/www/wpacracker/public_html/index.php:182 0.0024 248544 3. write_nets() /var/www/wpacracker/public_html/content/my_nets.php:33 Notice: Undefined index: n_state in /var/www/wpacracker/public_html/common.php on line 754 Call Stack: 0.0001 231480 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 236656 2. include('/var/www/wpacracker/public_html/content/my_nets.php') /var/www/wpacracker/public_html/index.php:182 0.0024 248544 3. write_nets() /var/www/wpacracker/public_html/content/my_nets.php:33 Notice: Undefined index: n_state in /var/www/wpacracker/public_html/common.php on line 754 Call Stack: 0.0001 231480 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 236656 2. include('/var/www/wpacracker/public_html/content/my_nets.php') /var/www/wpacracker/public_html/index.php:182 0.0024 248544 3. write_nets() /var/www/wpacracker/public_html/content/my_nets.php:33 Notice: Undefined index: n_state in /var/www/wpacracker/public_html/common.php on line 754 Call Stack: 0.0001 231480 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 236656 2. include('/var/www/wpacracker/public_html/content/my_nets.php') /var/www/wpacracker/public_html/index.php:182 0.0024 248544 3. write_nets() /var/www/wpacracker/public_html/content/my_nets.php:33 Notice: Undefined index: n_state in /var/www/wpacracker/public_html/common.php on line 754 Call Stack: 0.0001 231480 1. {main}() /var/www/wpacracker/public_html/index.php:0 0.0002 236656 2. include('/var/www/wpacracker/public_html/content/my_nets.php') /var/www/wpacracker/public_html/index.php:182 0.0024 248544 3. write_nets() /var/www/wpacracker/public_html/content/my_nets.php:33 `

I'm able to view the list of networks associated with my key (also defined as a bosskey), however the already cracked passwords are not displayed. I'm able to view them through the "Nets" view though.

**Comment by RealEnder** [comment]
Forget to commit that change, 10x for pointing out

**Comment by strasharo** [comment]
Thanks a lot for fixing it, it works now.
