### ISSUE TITLE
Crash client work

### ISSUE THREAD

**Issue by Botusau** [RealEnder/dwpa#4]
Hello. Sorry for my english. (Google translate)))
I analyzed your code and could not find a module responsible for processing emergency shutdown script or program on the client. The server does not received a negative response from the client thinks too much dictionary completed and not interrupted by the emergency.
This is true?

**Comment by RealEnder** [comment]
If I understood correctly, if there is a problem with client(help_crack), and it still hits get_work API, there is no way to detect this on server side and the actual capture is not checked against the dictionary.
This is correct and currently I can't detect such situations on server side.
I'm open for suggestions on this.

**Comment by RealEnder** [comment]
Partially fixed with the merge of `combine_same_essid` branch and handshake keys introduction.
