### ISSUE TITLE
Enhancement: download all networks for a given key

### ISSUE THREAD

**Issue by TenoTrash** [RealEnder/dwpa#45]
Hello,
Can an option for download all networks (solved ?) for a given key been added?
Thanks!

**Comment by RealEnder** [comment]
Do you think it will be useful for a user to download something like:
hash:type (hccapx/pmkid):bssid:mac_sta:essid (maybe in hex):PMK:PSK" ?

**Comment by strasharo** [comment]
Or it could be something like an API. That would help a lot, especially for users with a lot of networks. I'm currently at around 140 pages with networks and it's a real pain to check manually backwards what was cracked. If I could do something like a rest call to fetch them all at once and just parse them by myself from there on that would be awesome.

**Comment by RealEnder** [comment]
@strasharo the API is in TODO, but first we have to implement proper user management - right now the user key is just a "convenience" - not secure at all, as I presume that cracked.txt/rkg.txt are publicly available, nobody will want to see others submitted results.
It will be possible to script it, will try to get to it in next couple a days.

**Comment by TenoTrash** [comment]
I will to implemet something on my side using curl, what do you think?

**Comment by TenoTrash** [comment]
Still no way to download all networks from a given key...
Just use lynx and print to text file, then sort...
Any hint?

**Comment by TenoTrash** [comment]
> Do you think it will be useful for a user to download something like:
> hash:type (hccapx/pmkid):bssid:mac_sta:essid (maybe in hex):PMK:PSK" ?

This will be great!

**Comment by RealEnder** [comment]
You can find "Download all founds" button on the bottom of "My nets" page. The format is the default hashcat potfile.
As a bonus, here is how to pull it with wget:
`wget --content-disposition --header "Cookie: key=[YOUR_KEY]" "https://wpa-sec.stanev.org/?api&dl=1"`
