### ISSUE TITLE
No handshakes found.

### ISSUE THREAD

**Issue by jaws1932** [RealEnder/dwpa#46]
Got server setup correctly and everything works.  Uploaded a known good capture with many handshakes and PMKID (tested on your site).  However, help_crack.py reports no suitable nets found.  

Poking into the PHP on get_work.php, the code is dropping out at this part:

// get handshakes and prepare
    $stmt = $mysql->stmt_init();
    $stmt->prepare("SELECT net_id, struct, keyver
FROM nets n
WHERE ssid = BINARY (SELECT ssid
                     FROM nets
                     WHERE n_state=0 AND
                           algo=''
                     ORDER BY hits, ts
                     LIMIT 1) AND
      n_state=0 AND
      algo='' AND
      net_id NOT IN (SELECT net_id
                     FROM n2d
                     WHERE d_id IN (".implode(',', array_fill(0, $dc, '?')).") AND
                           n2d.net_id = n.net_id)");
    $ref[0] = str_repeat('i', $dc);
    call_user_func_array(array($stmt, 'bind_param'), $ref);
    $stmt->execute();
    $result = $stmt->get_result();
    $handshakes = $result->fetch_all(MYSQLI_ASSOC);
    $result->free();

    if (count($handshakes) == 0) {
        release_lock('get_work.lock');
        fclose($myfile);
        die('No nets');

So something is wrong with the return of handshakes from the MYSQL database, although the nets are showing on the website fine and the capture seemed to be correctly parsed.

**Comment by RealEnder** [comment]
What's the content of your dicts table? You can paste it without dict URLs. Also you should create empty cracked.txt.gz just in case.
To see what happen, you can execute the queries by hand like this:
```
SELECT d_id, HEX(dhash) as dhash, dpath
FROM dicts d
WHERE NOT EXISTS (SELECT d_id
                  FROM n2d
                  WHERE d.d_id=n2d.d_id AND
                        n2d.net_id=(SELECT net_id
                                    FROM nets
                                    WHERE n_state=0 AND
                                          algo=''
                                    ORDER BY hits, ts
                                    LIMIT 1))
ORDER BY d.wcount, d.dname
LIMIT 10
```
This is for dictionary selection. Then for nets:
```
SELECT net_id, struct, keyver
FROM nets n
WHERE ssid = BINARY (SELECT ssid
                     FROM nets
                     WHERE n_state=0 AND
                           algo=''
                     ORDER BY hits, ts
                     LIMIT 1) AND
      n_state=0 AND
      algo='' AND
      net_id NOT IN (SELECT net_id
                     FROM n2d
                     WHERE d_id IN (<put here d_id value, comma separated>) AND
                           n2d.net_id = n.net_id)
```
Also did you had errors running db creation and data insertion scripts?

**Comment by jaws1932** [comment]
Dicts table

`+------+----------------------------------+---------------------------------------------------------+
| d_id | dhash                            | dpath                                                   |
+------+----------------------------------+---------------------------------------------------------+
|   17 | 77A658E54EC8447A556023EB01500294 | https://----.com/dict/cracked.txt.gz                 |
|   20 | 493D7B319DD93ED3AF690024DBBCD332 | https://----.com/dict/probable-v2-wpa-top62.txt.gz   |
|   18 | 10E2E8BAFFDC58397219ACF9D249A387 | https://----.com/dict/probable-v2-wpa-top447.txt.gz  |
|   19 | FED9792480E64D4D311893A965CFB894 | https://----.com/dict/probable-v2-wpa-top4800.txt.gz |
|   16 | 5DEB1089D8310CC683A278FD4D19927A | https:/----.com/dict/bc16.txt.gz                    |
|   21 | 84079E88F3BB195243604DAEBBE0307F | https://----.com/dict/rockyou.txt.gz                 |
|    1 | A690AFA6CDEE00315A0165964A19F32D | https://----.com/dict/bc01.txt.gz                    |
|    2 | 627D35EC159005218329C73D55FF18CB | https://----.com/dict/bc02.txt.gz                    |
|    3 | 450D8F47049429BD6256DF111C0A1C21 | https://----.com/dict/bc03.txt.gz                    |
|    4 | 8071B082F053565882E8D2414396634F | https://----.com/dict/bc04.txt.gz                    |
+------+----------------------------------+---------------------------------------------------------+
10 rows in set (0.00 sec)`

I'm not sure what to put for the d_id value for the nets query.  I can query the nets table and return results.  Did not have any errors during creation or setup.

**Comment by RealEnder** [comment]
OK, figured it out. I missed to add running rkg.php in cron in documentation. By design, we first try to crack the nets with routerkeygenPC candidates, then what's left is released to crackers. There is example cron entry for this.
Alternatively, you can make column "algo" in nets table default empty string ('') on insert and update current rows also to empty string (eg. `update nets set algo=''`)
Will update the documentation.

**Comment by jaws1932** [comment]
That's funny, I actually just figured it out as well by doing some test mysql queries and came back to comment.  

I simply removed the algo='' references from the mysql queries in get_work.php.  The queries now look like this:
`$stmt->prepare("SELECT net_id, struct, keyver
FROM nets n
WHERE ssid = BINARY (SELECT ssid
                     FROM nets
                     WHERE n_state=0
                     ORDER BY hits, ts
                     LIMIT 1) AND
      n_state=0 AND
      net_id NOT IN (SELECT net_id
                     FROM n2d
                     WHERE d_id IN (".implode(',', array_fill(0, $dc, '?')).") AND
                           n2d.net_id = n.net_id)");
`

**Comment by RealEnder** [comment]
Yep, this will do the trick, but that way you end up with more changes, algo is checked in other queries, if you wan to skip just change the default column.

**Comment by jaws1932** [comment]
Added contents of rkg.cron to system crontab and all works well.  RKG cleans up the database and changes the algo from NULL to empty string.

`cat ~/dwpa/misc/rkg.cron >> /etc/crontab`
