### ISSUE TITLE
Installing Problems on Kali

### ISSUE THREAD

**Issue by tsiebecker** [RealEnder/dwpa#47]
Followed the instructions, but I've encountered a problem.
Calling localhost//?nets shows just      

`Fatal error: Uncaught Error: Call to undefined function mysqli_init() in /var/www/html/db.php:5 Stack trace: #0 /var/www/html/content/nets.php(2): require_once() #1 /var/www/html/index.php(182): include('/var/www/html/c...') #2 {main} thrown in /var/www/html/db.php on line 5`

how do i enable the mysqli extension for the php script?

**Comment by strasharo** [comment]
Do you have the php-mysql package installed?
If not should be something like apt-get install php-mysql. Or if you're running php7 it would be apt-get install php7.3-mysql.

**Comment by tsiebecker** [comment]
okay, i found it.
Ill leave a link in case someone else has the same difficulties.
[https://medium.com/@jangid.hitesh2112/how-to-install-lamp-stack-on-kali-linux-183fa4f48d16](url)

apt remove --purge *apache*
apt remove --purge *php*
apt remove --purge *sql*

apt install apache2 
apt install default-mysql-server 
apt install php7.3
apt install *sqlnd*  <--- this one was definitly missing

do info.php trick to get loaded config dir of php ( in my case /etc/php/7.3/apache2/php.ini AND /etc/php/cli/php.ini )
edit BOTH php.ini , find ";extension=mysqli" and uncomment it. 
make sure in /etc/php/7.3/apache2/conf.d/ AND /etc/php/cli/conf.d/ 
are 10-mysqlnd.ini with extension=mysqlnd.so and 20-mysqli.ini with extension=mysqli.so uncommented present.
if not check the mods-available folder and the actual installed packets on your system

**Comment by tsiebecker** [comment]
doesn't apt-get install php-mysql also install all perl and python libs?
okay i mean apt install default-mysql-server on kali is not really better, because maria-db gets installed too. In this case, however, I wanted it that way, otherwise I would have found another solution.
And of course thanks for the effort
