### ISSUE TITLE
Hi Alex, Help please

### ISSUE THREAD

**Issue by kabaka14** [RealEnder/dwpa#5]
First thing, Thank you for this script of WPA it's Amazing Script
i did upload the script on my website but I don't know how I can install it,
I don't know what is the nest step??! it's link can you check it and tell me what I can do?
http://www.teste03.com.br/dwpa/web/?dicts

can you give me video for how I can install it??! 

Thank you.

**Comment by RealEnder** [comment]
Please check [INSTALL.md](https://github.com/RealEnder/dwpa/blob/master/INSTALL.md) for instructions.
