### ISSUE TITLE
New hashcat beta doesn't work

### ISSUE THREAD

**Issue by tsiebecker** [RealEnder/dwpa#50]
I tried to run the newest hashcat beta (new optimizations, see [https://www.bitcrack.net/new-hashcat-optimization-faster-maxwell-cards/](https://www.bitcrack.net/new-hashcat-optimization-faster-maxwell-cards/) )
from here:
[https://hashcat.net/beta/](https://hashcat.net/beta/)
but help_crack.py shows
```
Challenge cracker for correct results
Challenge solving failed! Check if your cracker runs correctly.
```
Any idea how to solve this?

**Comment by RealEnder** [comment]
This is because of new hash-mode-plugin. When it's released I'll add the needed functionality for this.

**Comment by RealEnder** [comment]
It's in current HEAD, please test.

**Comment by InfoSecOne** [comment]
Hi, 
I have the same issue when I try to re-run the python file from a command line. To replicate:
1) run the helper.py file 
2) wait some time (5min)
3) hit 'q' for quit hashcat
4) rerun the command 
5) visible error 'Challenge solving failed! Check if your cracker runs correctly.' 

There is no logfile so I can't check the issue for details. I was trying to remove the --no-debug from the script but no luck. 

The only way to fix this issue on my laptop is to delete all the files from the folder, re download the script and re-run it again.

**Comment by RealEnder** [comment]
Looks like hashcat installation issue. Please try to run `hashcat -b -m2500` to confirm. If this fails, check hashcat install, eg. remove old compiled kernels. If the issue is not there, please open another issue.
10x!
