### ISSUE TITLE
Download All Found button not working after last update

### ISSUE THREAD

**Issue by TenoTrash** [RealEnder/dwpa#54]
Hello there!

The "download all found" button not seems to work anymore

This has in return:

`stmt_init(); $stmt->prepare('SELECT nets.bssid AS bssid, nets.mac_sta AS mac_sta, nets.ssid AS ssid, nets.pass AS pass FROM nets, n2u, users WHERE nets.net_id=n2u.net_id AND nets.n_state=1 AND users.u_id=n2u.u_id AND users.userkey=UNHEX(?) ORDER BY nets.ts'); $stmt->bind_param('s', $k); $stmt->execute(); stmt_bind_assoc($stmt, $data); while ($stmt->fetch()) { printf("%s:%s:%s:%s\n", long2mac($data['bssid'], ''), long2mac($data['mac_sta'], ''), $data['ssid'], $data['pass']); } $stmt->close(); $mysql->close(); } ?> `

**Comment by RealEnder** [comment]
It was server configuration issue, 10x
