### ISSUE TITLE
Simplify API instructions 

### ISSUE THREAD

**Issue by ProjectZeroDays** [RealEnder/dwpa#55]
wlancap2wpasec -u https://api.onlinehashcrack.com -e youremail@whatever.com handshake_ESSID_TH-EM-AC-AD-DR-ES_THE-DATE-OF-CAPTURE.cap

**Comment by ProjectZeroDays** [comment]
wlancap2wpasec -u https://api.onlinehashcrack.com -e myemail@gmail.com handshake_IAmNotHome.cap

**Comment by Czechball** [comment]
I think you're in the wrong repo, the one you want is https://github.com/ZerBea/hcxtools - I suggest you post the issue there

**Comment by RealEnder** [comment]
Not a wpa-sec issue.
