### ISSUE TITLE
rkg.php crontab failing

### ISSUE THREAD

**Issue by kbeflo** [RealEnder/dwpa#59]
My `rkg.php` entry failing on my crontab config. Causing `help_crack.py` to go to sleep and no suitable nets found. 

If I manually run `sudo -u www-data /usr/bin/php /var/www/wpa-sec/rkg.php`, hc returns to cracking. 

Crontab entry:

`sudo crontab -u www-data -e`

```
*/5 * * * * www-data cd /var/www/wpa-sec && /usr/bin/flock -n /tmp/rkg.php.lock /usr/bin/php rkg.php
```
                                        
/tmp/rkg.php.lock file does not exist.
                                                         
syslog shows that it's running every 5 minutes
```
CRON[4187]: (www-data) CMD (www-data cd /var/www/wpa-sec && /usr/bin/flock -n /tmp/rkg.php.lock /usr/bin/php rkg.php)
```

I'm trying a workaround following https://serverfault.com/a/978728/483581 by manually running 

`sudo -u www-data /usr/bin/flock -n /tmp/rkg.php.lock /usr/bin/php /var/www/wpa-sec/rkg.php`

and

`sudo chmod 666 /tmp/rkg.php.lock`

**Comment by RealEnder** [comment]
Hm, missed this one. Anyways, did you managed to solve it? What happens when you run it by hand?
The lock file is created only when rkg.php is processing nets, so if you have small DB it will just finish very fast.

**Comment by kbeflo** [comment]
I haven't found a solution yet. I still manually run 

`sudo -u www-data /usr/local/bin/php /var/www/html/rkg.php`

and wait for a couple of minutes to start on my docker fork.

**Comment by RealEnder** [comment]
Maybe just remove this from crontab of www-data user and put it in root's one. This will still run as www-data, as defined in the crontab file. Ie like `sudo crontab -e`

**Comment by kbeflo** [comment]
I redid testing today using my docker fork and now it runs smoothly. I shouldn't have to manually run rkg.php in the first place.
