### ISSUE TITLE
Permissions issue with pyrit

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#6]
After following the install instructions I bumped again in the issue described here:
https://github.com/RealEnder/dwpa/issues/3 

After some troubleshooting I found out the reason for it:

```
root@scw-e84a16 public_html]# sudo -u apache pyrit
Traceback (most recent call last):
  File "/bin/pyrit", line 4, in <module>
    import pyrit_cli
  File "/usr/lib64/python2.7/site-packages/pyrit_cli.py", line 33, in <module>
    import cpyrit.cpyrit
  File "/usr/lib64/python2.7/site-packages/cpyrit/cpyrit.py", line 42, in <module>
    import util
  File "/usr/lib64/python2.7/site-packages/cpyrit/util.py", line 56, in <module>
    import config
  File "/usr/lib64/python2.7/site-packages/cpyrit/config.py", line 69, in <module>
    os.makedirs(configpath)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/share/httpd/.pyrit'
```

I know that this is an external tool and the issue is not related to dwpa itself, but I guess it will be helpful to add a tip to the installation notes that the user should create the pyrit profile dir for the webserver user manually and ensure that it's accessible by it.

**Comment by RealEnder** [comment]
Good catch!
pyrit is currently used only for wpa handshake validation after wpaclean. Will check it out if it is still needed, and will try to improve wpaclean if this is the case. Otherwise will just drop it.

**Comment by RealEnder** [comment]
In most cases pyrit is unneeded. The whole handshake identification will move to [hcxtools](https://github.com/ZerBea/hcxtools), so this will go by itself.

**Comment by strasharo** [comment]
Since pyrit is already removed this is no longer relevant.
