### ISSUE TITLE
Support of Hashcat v.6

### ISSUE THREAD

**Issue by k4nfr3** [RealEnder/dwpa#62]
Hi, 
hashcat v6 has performance improvements which can be beneficial to the project.
but I'm encountering issues in the tests. 
Regards

**Comment by RealEnder** [comment]
Yes, the potfile format has changed with v6. Will try to fix it shortly, but main focus will be to move the internal storage to -m 22000 format.

**Comment by RealEnder** [comment]
Fixed in help_crack v1.1.1
