### ISSUE TITLE
Allow submission of hashcat .22000 file format

### ISSUE THREAD

**Issue by DaniloNC** [RealEnder/dwpa#64]
The 22000 format is great to work with text editors, grep for specific networks and is relatively small when compared to .cap files.

Please consider adding the option to upload .22000 file format directly.

**Comment by RealEnder** [comment]
We are interested in raw capture files, so we can improve handshake and PMKID identification techniques. In the raw captures, if sniffed/created with the right tools (hcxdumptool) you can find valuable information and even raw passwords.

**Comment by DaniloNC** [comment]
Just in case someone needs to upload and all that you have is the .22000 file.
Requirements: hcxtools installed. 

```bash
#!/bin/bash

##
#  Read a .22000 from stdin and upload to wpasec the .cap files
#  the command options are passed to wlancap2wpasec.
#  example cat hash.22000 | bash wpasec_22000_sin.sh -k <YOUR_WPASEC_KEY>
##
TMPFILE=$(mktemp --suffix=.22000)
TMPDIR=$(mktemp -d --suffix="-caps")

cat | tee "$TMPFILE"

pushd "$TMPDIR"
hcxhash2cap --pmkid-eapol="$TMPFILE"
wlancap2wpasec "$@" $TMPDIR/*
popd

rm -rf "$TMPDIR" "$TMPFILE"
```
