### ISSUE TITLE
Add additional usage instructions

### ISSUE THREAD

**Issue by FractumSeraph** [RealEnder/dwpa#66]
I'm unable to find much information on the Github to run the script with any other options. The specific option I'm looking for is to use a custom dictionary. 
I see it mentioned in the file at [line 860](https://github.com/RealEnder/dwpa/blob/master/help_crack/help_crack.py#L860), but I have no idea how to actually add the argument to make the script use it.

**Comment by RealEnder** [comment]
Just run help_crack,py -h for the list of options.
As for the dictionaries, there are two options currently:
-ad , which is additional user dictionary, which will be added to wpa-sec ones during a normal run. This is preferred.
-cd is custom dictionary, to be used against all uncracked hashes, grouped by essid. This is currently suboptimal and will be reworked in future versions. But it should work for now.
