### ISSUE TITLE
can't start help_crack

### ISSUE THREAD

**Issue by nimbo78** [RealEnder/dwpa#67]
just trying to start on AMD Ryzen 3500X+RX580 Windows Home x64:

C:\Users\igors\Downloads\hashcat-5.1.0>help_crack.py
C:\Users\igors\Downloads\hashcat-5.1.0>
and nothing happens. if trying to run from Explorer: new terminal window appears and closes.

any guide?

**Comment by RealEnder** [comment]
Please download the last hashcat version 6.1.1. Also, did you installed python?

**Comment by nimbo78** [comment]
> Please download the last hashcat version 6.1.1. Also, did you installed python?

Well, I've tried hashcat 5.1.0 and 6.1.1, python version x64 3.9.0

**Comment by RealEnder** [comment]
Try with 32bit python - at least it should spill some error. Please run it from command prompt, so we can see what the error is.

**Comment by nimbo78** [comment]
> 
> 
> Try with 32bit python - at least it should spill some error. Please run it from command prompt, so we can see what the error is.

with 32bit python all good. well, problem with python 64bit?

**Comment by RealEnder** [comment]
Nope, just a check in help_crack, which tries to identify what platform we're running and then execute the right binary. Will fix this shortly.
