### ISSUE TITLE
Possibility for using local wordlists only 

### ISSUE THREAD

**Issue by Vyndar** [RealEnder/dwpa#68]
Is there a way to remove the dictionary download part ? I have a spare PC that can run Hashcat all day but I prefer to use my own wordlists.

**Comment by RealEnder** [comment]
Please try the -cd option of help_crack.py

**Comment by Vyndar** [comment]
When using the -cd command I get this error: https://prnt.sc/w0jtmq 
Also, how can I select multiple dictionaries because that doesn't seem to work either it just says invalid argument.

**Comment by RealEnder** [comment]
This should be fixed now. You may also use the latest help_crack.py from git's HEAD.

**Comment by Vyndar** [comment]
Works fine now, thanks ! Closing this now.

**Comment by ZerBea** [comment]
Nice fix. That (user defined dictionaries) will make wpa-sec more dynamic than using every time the same ones.
