### ISSUE TITLE
Suggestion: Don't extract wordlists in help_crack.py

### ISSUE THREAD

**Issue by Czechball** [RealEnder/dwpa#69]
Right now, help_crack downloads *and* extracts wordlists. This generates mess in the working directory and is not needed at all, since hashcat can process gzip'd wordlists directly. I think it would be nice to entirely skip the extracting process and just use the downloaded wordlists as they are.

**Comment by RealEnder** [comment]
Agreed for the mess, but I have issues with our compressed dicts - hashcat just don't decompress them when I last tried. Did you tried with our dicts? What's the result?

**Comment by Czechball** [comment]
Oh, you're right... Wordlists downloaded directly from https://wpa-sec.stanev.org/?dicts aren't extracted correctly by Hashcat, only when I re-gzip them... weird

**Comment by RealEnder** [comment]
Will take a look at hashcat's decompress code to see what happens. For John we still have to decompress the dicts.

**Comment by RealEnder** [comment]
Found the gz issue in hashcat and submitted a PR hashcat/hashcat#2668

**Comment by Czechball** [comment]
Nice!

**Comment by Wingman4l7** [comment]
This looks like it finally got merged into hashcat, so it can be fixed on this side now.

**Comment by RealEnder** [comment]
Fixed in help_crack.py 2.0.0. If hashcat is the selected cracker, the wordlists will not be decompressed.
