### ISSUE TITLE
no suitable nets found

### ISSUE THREAD

**Issue by Banthex** [RealEnder/dwpa#74]
Hello,

I'm playing around with an instance of dwpa.
I followed the whole guide, but when my worker wants to challenge the cracker for correct  results, I'm getting the message "no suitable nets found". 
Is this maybe a problem with the web server file rights?

Thanks in advance.
Banthex

**Comment by RealEnder** [comment]
Hi,
This is the message when all dicts were tried against all submitted nets. Also you'll need to cron rkg.php script, which after trying with routerkeygen releases nets for the crackers.

**Comment by Banthex** [comment]
Hello,

thank you very much, I fixed it with this information. My cronjob had the wrong rights.

Greetings and stay healthy!

**Comment by RealEnder** [comment]
Great!
