### ISSUE TITLE
hash mode 2500 and hash mode 16800 are deprecated - help_crack.py will not work any longer

### ISSUE THREAD

**Issue by ZerBea** [RealEnder/dwpa#75]
Atom started to replace deprecated hash modes 250x and 1680x by the new hash mode 22000.
Updating to latest hashcat git head will let help_crack.py not work any longer: 

```
$ ./help_crack.py -dc 1
Choose the tool for cracking:
0: /usr/bin/hashcat
9: Quit
Index:0
Challenge cracker for correct results
The plugin 16800 is deprecated and was replaced with plugin 22000. For more details, please read: https://hashcat.net/forum/thread-10253.html

hashcat /usr/bin/hashcat died with code 255
Check you have OpenCL support
```

**Comment by FFAMax** [comment]
Download old hashcat, untar `tar -xf hashcat-5.1.0.tar`
Compile:
```
cd hashcat-5.1.0/
make build
```
Put help_crack.py in the same directory.
Modify path to hashcat: `'./hashcat'` instead of `'hashcat'`
Or put here absolute path to your custom build.

**Comment by ZerBea** [comment]
Or simply add this:
`--deprecated-check-disable`

From hashcat help:
```
$ hashcat --help | grep depr
     --deprecated-check-disable |      | Enable deprecated plugins                            |
```

**Comment by mcauser** [comment]
ie. `help_crack.py -co="--deprecated-check-disable"`

**Comment by SaleSlave** [comment]
plz include .bat file ""

**Comment by RealEnder** [comment]
This is fixed in help_crack.py version 2.0.0.
Please update.
