### ISSUE TITLE
The plugin 16800 is deprecated and was replaced with plugin 22000

### ISSUE THREAD

**Issue by opastorello** [RealEnder/dwpa#76]
Challenge cracker for correct results
cuFuncSetAttribute is missing from CUDA shared library.

The plugin 16800 is deprecated and was replaced with plugin 22000. For more details, please read: https://hashcat.net/forum/thread-10253.html

hashcat hashcat.exe died with code 4294967295
Check you have OpenCL support

> I changed 16800 to 22000, and also changed 2500 to 22000.

Challenge cracker for correct results
cuFuncSetAttribute is missing from CUDA shared library.

cuFuncSetAttribute is missing from CUDA shared library.

No hashes loaded.

hashcat hashcat.exe died with code 4294967295
Check you have OpenCL support

> hashcat v6.2.4

**Comment by RealEnder** [comment]
Duplicates #75 
For now please use option `-co="--deprecated-check-disable"` to help_crack.py
