### ISSUE TITLE
i wont to delete my uplouds on https://wpa-sec.stanev.org/

### ISSUE THREAD

**Issue by t-code-now** [RealEnder/dwpa#78]
hi please i need your help.

i uplouded some handshakes to the https://wpa-sec.stanev.org/ website.
i want to delete tham from there please,
can you do it?

**Comment by Wingman4l7** [comment]
True, but deletion would mitigate the leak; changing the WiFi key may not be possible (example: WiFi network could be a friend's household network, sniffed accidentally because it was not whitelisted on a pwnagotchi).

**Comment by Tamirmaidani** [comment]
Thank you all the issue as been solved..the owner has changed what has been
needed to change..thanx

בתאריך שבת, 1 בינו׳ 2022, 01:13, מאת Wingman4l7 ***@***.***>:
