### ISSUE TITLE
Cracking hashes on Google Colab. [Not an issue]

### ISSUE THREAD

**Issue by FractumSeraph** [RealEnder/dwpa#79]
Google Colab is capable of running help_crack.py. It works on free accounts, you will just get deprioritized after a while.  I don't use Colab for anything else, so this doesn't bother me.  Just thought I'd post this in case anyone else was interested.

[Link removed by OP]

**Comment by RealEnder** [comment]
Thanks for your contribution! Hope this is not against Colab's terms of usage.
Will keep this open for now, so other users can see it.

**Comment by funkymonkey5150** [comment]
Thanks for info

**Comment by funkymonkey5150** [comment]
You good

**Comment by strasharo** [comment]
> Hope this is not against Colab's terms of usage.
Looks like it is :(
![image](https://user-images.githubusercontent.com/3337997/182677278-89940392-a376-4faf-b398-931489ced0c1.png)

**Comment by FractumSeraph** [comment]
> > Hope this is not against Colab's terms of usage.
> 
> Looks like it is :( ![image](https://user-images.githubusercontent.com/3337997/182677278-89940392-a376-4faf-b398-931489ced0c1.png)

That unfortunate.  I believe I checked at the time and it just said it would be deprioritized of something similar.  Must've changed at some point.
