### ISSUE TITLE
Wigle links broken

### ISSUE THREAD

**Issue by strasharo** [RealEnder/dwpa#8]
Looks like Wigle recently deprecated their old API at https://www.wigle.net/gps/gps/main/confirmquery and the URL now gives 404. I've asked them what's going on and they responded with this:
https://wigle.net/phpbb/viewtopic.php?f=1&t=1516&p=9380#p9379

> Hey strasharo - that endpoint was a part of the very, very old non-API. 
> 
> We tried to give everyone ample warning, but finally took it offline for good a few weeks ago. This allowed us to jettison some old, hard-to-support code, as well as improve efficiency and performance on all the queries people like to make. We have a new API (see https://api.wigle.net for all the details) - that we're proud to publish and support, and there's already a blossoming community of packages that allow you to simply plug it into your project of choice.
> 
> If you're looking for UI equivalents, [url]https://wigle.net/search[/url], [url]https://wigle.net/search#detailSearch[/url], and [url]https://wigle.net/mapsearch[/url] should contain all the functionality present in that endpoint.
> 
> If there's something we failed to port over, or it's not working for you, this is a good place to tell us;; obviously we didn't intent to disable any functionality.
> 
> Cheers,
> 
> -a

I'll have a look and see if I can help with a PR for this.

**Comment by RealEnder** [comment]
Fixed in 73e92ddbf51a3661c73d0852dfc5b50532e66f09
Thanks for the points!

**Comment by strasharo** [comment]
Thanks a lot.
