### ISSUE TITLE
hcxpcaptool vs hcxpcapngtool

### ISSUE THREAD

**Issue by k4nfr3** [RealEnder/dwpa#82]
Hi,

in https://github.com/RealEnder/dwpa/blob/master/INSTALL.md
Should the binary not be hcxpcapngtool ? 

In my instance i have 6.0.2 as  hcxpcaptool  but 6.2.6-1 as hcxpcapngtool

Any advice ?

Regards

**Comment by RealEnder** [comment]
wpa-sec uses hcxpcapngtool since it's introduction. The install file wasn't touched since a long time, will fix it.
Thanks for the heads-up.

**Comment by RealEnder** [comment]
Fixed with [3e11785](https://github.com/RealEnder/dwpa/commit/3e1178536396bf7aebe82d63e24e51337977a5f5)
