### ISSUE TITLE
Get Success Information

### ISSUE THREAD

**Issue by ShredRum** [RealEnder/dwpa#83]
Hello.  I'm interested in the question, how can I find out how many passwords I managed to crack without watching the program?  Perhaps there is a possibility to write them in a potfile?  Thank you.  This post was written using google translator.  please ignore the mistakes.

**Comment by RealEnder** [comment]
Hi, you can use `-pot` option of help_crack.py. Just execute it like this:
`python help_crack.py -pot my_wpa-sec.pot`
