### ISSUE TITLE
Capture processing error. Exit code 127. Please inform developers.

### ISSUE THREAD

**Issue by Gualty** [RealEnder/dwpa#84]
Hi,
I created my instance of dwpa, all works fine until the upload of the first pcap file.
After I upload it an error message appear: "Capture processing error. Exit code 127. Please inform developers."

I tried also to upload manually a file on the server, convert the file in hash format 22000 using the builded "**hcxpcapngtool**" in the _cap_ folder and then use hashcat. Those tools are working via command line.

Same file uploaded on https://wpa-sec.stanev.org/ works fine

What can be the issue?

**Comment by RealEnder** [comment]
Hi,
hcxpcapngtool deprecated and removed some of the options we used in the past.
Please change the line
https://github.com/RealEnder/dwpa/blob/master/web/common.php#L449
with
`exec(HCXPCAPTOOL." --nonce-error-corrections=8 --eapoltimeout=20000 --max-essids=1 --hccapx=$hccapxfile --pmkid=$pmkidfile $file 2>&1", $res, $rc);`

**Comment by Gualty** [comment]
Thank you! It's working!
