### ISSUE TITLE
help_crack.py

### ISSUE THREAD

**Issue by Eetuheino03** [RealEnder/dwpa#86]
Hello, i downloaded python script and i try run it whit hashcat because cracking gpu is better but its says "hashcat /usr/bin/hashcat died with code 255
Check you have OpenCL support" i have downloaded drivers and cuda-toolkit and i can run hashcat in opencl mode but it still says that?

GPU is rtx 3060 tuf gaiming ver 2 lhr
CPU intel i7 11 gen k
SYSTEM Kali linux latest
Python3 lates in use

**Comment by its0x08** [comment]
I have the same issue, besides the error of the deprecated plugin!
Though I use hashcat manually and I never get such error!!

**Comment by RealEnder** [comment]
Please try to add `-co="--deprecated-check-disable"` to help_crack.py

**Comment by Eetuheino03** [comment]
Do you mean that I don't change code just add it behind "python help_crack.py -co="--deprecated-check-disable" "

**Comment by its0x08** [comment]
It kinda works 😃

**Comment by RealEnder** [comment]
This just enables hashcat to use m2500/m16800. he original plugins are still not killed, just hidden. Of course, there will be a proper fix for this.

**Comment by its0x08** [comment]
Just append ` -co="--deprecated-check-disable"` and everything would be ok.

**Comment by IntentionalQuintessence** [comment]
Thank you.

**Comment by its0x08** [comment]
I think this should be added to the README.md and the help menu  of the tool!
Would be easier for people to fix the hashcat error. Probably this problem pushes 
away a lot of contributors everyday.

> Please try to add `-co="--deprecated-check-disable"` to help_crack.py
