### ISSUE TITLE
custom wordlists

### ISSUE THREAD

**Issue by Eetuheino03** [RealEnder/dwpa#87]
its not problem but can i use custom word lists because i see that help_crack.py script is checking them?

**Comment by IntentionalQuintessence** [comment]
I concer

**Comment by RealEnder** [comment]
Yep, you can use the `-ad` option of help_crack.py to pass an additional wordlist, which will be checked against the pulled hashes.

**Comment by IntentionalQuintessence** [comment]
Ok, thanks.
