### ISSUE TITLE
Search for string limited to 20 matches.

### ISSUE THREAD

**Issue by AlexHilgertBRA** [RealEnder/dwpa#9]
I think it would be useful for research to download some specific uncracked networks(finished) using search option. Additionally, search only show the first 20 matches if we use the SSID, but it shows all, if we use the part of mac address.

Best regards, Alex Hilgert.

**Comment by RealEnder** [comment]
Not very thrilled about direct handshake download - this can be abused.
Enforcing search limit is a bug, will fix it, 10x.

**Comment by AlexHilgertBRA** [comment]
I understand your point, thank you.
