### ISSUE TITLE
Stuck after key found

### ISSUE THREAD

**Issue by FFAMax** [RealEnder/dwpa#90]
Hey Alex. I saw last time process is stuck due network issue. Now catched it stuck right after Key found:
Key for bssid c8:***:80 is: !****x
And nothing next going. Last time I used `timeout` but that's not a right solution.
Do you know something about that?

```
 Ss   Apr24   0:01 SCREEN
 Ss   Apr24   0:00  \_ /bin/bash
 S+   Apr24   0:35      \_ python3 help_crack.py
```
I believe stuck here
```
    return self._sslobj.read(len, buffer)
```

UPD: Significant delay during `POST /?get_work=1.1.1` or `POST /?put_work`
Probably rely on long db query request, could you please check on current database for time execution/indexes?

UPD: Yeah, looks so. Catched `Warning: mysqli::real_connect(): (HY000/1040): Too many connections in /var/www/wpa-sec/db.php on line 8`

**Comment by RealEnder** [comment]
Yep, this was temporary serverside problem, now should be OK.
