### ISSUE TITLE
Feature request: rules support

### ISSUE THREAD

**Issue by FFAMax** [RealEnder/dwpa#91]
Hi Team. What do you think about rules support?
I found significant benefit of using rules instead of dictionaries in cases of 8-9 symbols numbers.

- This approach reduce overhead and allow to utilize GPU more efficiency (20-30%).
-  Less time on sync with a server (especially if server is busy). Just take 1 task and work on it the next hour(s).
- Allow to reduce CPU utilization (in case of using slow or limited CPU).

**Comment by RealEnder** [comment]
Hi, thanks for the suggestion. Using rules is currently possible through _co_ option, like this:
`./help_crack.py -co="-r rules/best64.rule"`

**Comment by FFAMax** [comment]
Also I feel to clarify the goal.
The ideal case is to have list of uncracked hashes loaded to GPU with a simple rule (-a 3 <rule>) applied [or advanced rules with -r <rules.file>]
This allow to efficiency continue work inside on GPU without interruptions on hash update or dict loadings (from server or toward GPU - both are decreasing efficiency as well as hashcat restart).

1. Download hashes
2. Init hashcat only once (hashes + rule | hashes + dict)
3. Submit once complete

**Comment by denizalsancak** [comment]
I am studying at university in Turkey. We have assignments on wps network security. I have attached two handshake files. how can i decrypt it. gpuhash.me finds it in 30 seconds. but I can not see. will anyone help?

https://www.mediafire.com/file/h7k00fk1e4ep3p0/wpa.rar/file

**Comment by Backtix** [comment]
How about submitting it to RealEnder's site [(wpa-sec.stanev.org)](https://wpa-sec.stanev.org) instead of hijacking the issue tracker?

[Get a key](https://wpa-sec.stanev.org/?get_key) and save it.
[Submit your cap](https://wpa-sec.stanev.org/?submit)
Wait.
Profit.

**Comment by denizalsancak** [comment]
no one helps with a completely legal issue

**Comment by RealEnder** [comment]
This is more of hcxdumptool question. Most likely these adapters will work, depending on drivers used/kernel versions.
Just try them with latest hcxdumptool and submit any issues in its github tracker. More info on adapters here: https://github.com/ZerBea/hcxdumptool#adapters

**Comment by RealEnder** [comment]
Rules support was added with 0a163ca and 00b7fbc.
Thanks for the idea!
