### ISSUE TITLE
Wpa help me

### ISSUE THREAD

**Issue by denizalsancak** [RealEnder/dwpa#93]
I am an survivor an university girl student. Our houses were destroyed and we moved to another city, but I can't access the internet. I captured the WPA handshake by watching videos of a remote wireless network. Gpuhash.me found the password in 50 seconds. But I can't see the password and I'm having a hard time finding anyone who can help. Everyone is on vacation in there is no one. There is no nearby network where I can ask for the password. I have uploaded the files please help https://
www.mediafire.com/file/gj6th4i8apymtan/
wpa.rar/file

completely legal. internet wifi is too far away. And everyone is on vacation. We are staying at the university. public wifi but no one to get the password.

**Comment by Wingman4l7** [comment]
TP-Link_B73F : 42079675
ZyXEL_HGW_4K4CN : [not found yet]

**Comment by RealEnder** [comment]
Please keep this outside the issue tracker.
